<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260224190639 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE grid (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, grid_power DOUBLE PRECISION DEFAULT NULL, solar_power DOUBLE PRECISION DEFAULT NULL, grid_power_day DOUBLE PRECISION DEFAULT NULL, invertor_power_day DOUBLE PRECISION DEFAULT NULL, grid_power_week DOUBLE PRECISION DEFAULT NULL, invertor_power_weel DOUBLE PRECISION DEFAULT NULL, grid_power_month DOUBLE PRECISION DEFAULT NULL, price DOUBLE PRECISION NOT NULL, solal_price DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE room (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, light_on BOOLEAN NOT NULL, atemperature DOUBLE PRECISION NOT NULL, noise_level DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE grid');
        $this->addSql('DROP TABLE room');
    }
}
